### ISSUE TITLE
How can i know last position was read?

### ISSUE THREAD

**Issue by thanhpdhe141032** [osheroff/mysql-binlog-connector-java#115]
I'm developing 1 java application to reading a binlog file to catch query event. Everything would be fine without exception. But what will happen if my application was crashed, i will miss many event to from my database. So I wonder how can I know the last position was before my application stopped and started at that position when I recover my app.

**Comment by zy1263188600** [comment]
![image](https://github.com/osheroff/mysql-binlog-connector-java/assets/74887513/e8ff36f2-a5bc-408b-864f-7c2e27412e67)
