### ISSUE TITLE
Question on multi sources

### ISSUE THREAD

**Issue by kokmike** [osheroff/mysql-binlog-connector-java#12]
Hello,

MySQL support multiple source db to one slave by using some channel to replicate data, is this supported by binlog extraction ?  Or maybe we could use one binlogClient for each source ?

Thank you.

**Comment by osheroff** [comment]
it's not supported natively.  You could either:

- use mysql to replicate to the slave, turn on `log_slave_updates`, replicate off that, or
- use one client per source.
