### ISSUE TITLE
Can the last_committed field be added when parsing gtidEvent events?

### ISSUE THREAD

**Issue by kjyyc** [osheroff/mysql-binlog-connector-java#129]
Here is the content of a binlog file:
![Snipaste_2023-11-01_17-11-48](https://github.com/osheroff/mysql-binlog-connector-java/assets/13294906/4624b960-cc1b-4b91-a6ae-c227558864ed)

Currently, there is no event that can obtain the last_committed field. I need to use this field to parallel replay SQL to the target MySQL. 

I hope this tool can add this field to 'gtid_event'.
<img width="854" alt="image" src="https://github.com/osheroff/mysql-binlog-connector-java/assets/13294906/1e463fc5-ee85-413b-b94b-0eb737d032ac">

PS:
mysql binary event:
<img width="732" alt="image" src="https://github.com/osheroff/mysql-binlog-connector-java/assets/13294906/c9b7b9c5-8490-4068-b389-e64a301f7792">

**Comment by methodmissing** [comment]
references WIP https://github.com/osheroff/mysql-binlog-connector-java/pull/130

**Comment by Naros** [comment]
This should be fixed in 0.29.0 @kjyyc, closing.
