### ISSUE TITLE
version 0.30.0 not published to Maven

### ISSUE THREAD

**Issue by flozano** [osheroff/mysql-binlog-connector-java#150]
https://search.maven.org/artifact/com.zendesk/mysql-binlog-connector-java
<img width="932" alt="image" src="https://github.com/user-attachments/assets/85053873-325a-443d-baa0-ca96bffd81a8">

**Comment by Naros** [comment]
Hi @flozano, as discussed with @osheroff, Debezium is now publishing releases of this artifact moving forward.  

You can find the `0.30.0` release at `io.debezium:mysql-binlog-connector-java:0.30.0`, or [here](https://repo1.maven.org/maven2/io/debezium/mysql-binlog-connector-java/0.30.0/).

**Comment by flozano** [comment]
oh ok, I didn't notice about the coordinate change. Thanks for the clarification!

**Comment by leiless** [comment]
FYI,

https://github.com/debezium/mysql-binlog-connector-java
https://mvnrepository.com/artifact/io.debezium/mysql-binlog-connector-java
