### ISSUE TITLE
Unsigned integer opt

### ISSUE THREAD

**Issue by zzt93** [osheroff/mysql-binlog-connector-java#16]
I am a developer of data sync tool and I am trying to simplify the config that a user of sync tool needed to do. For example, if user need to backup a database using binlog method, it may use our tool. User has to do some conversions during the sync process,  because of the unsigned integer.

```sql
CREATE TABLE IF NOT EXISTS  `simple_type` (
	`id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	`tinyint` tinyint UNSIGNED NOT NULL,
        ...,
	PRIMARY KEY (`id`)
)
```
Because the connector default read `(unsigned) tinyint`, `(unsigned) smallint` etc to `int`,
```java
    protected Serializable deserializeTiny(ByteArrayInputStream inputStream) throws IOException {
        return (int) ((byte) inputStream.readInteger(1));
    }

    protected Serializable deserializeShort(ByteArrayInputStream inputStream) throws IOException {
        return (int) ((short) inputStream.readInteger(2));
    }
```
it seems that sync tool has no way to know what exactly the type it represents, or even the size. I am little bit confused whether the `int` cast can be removed, in which case, we can convert it to hex string according to byte count when output to MySQL (Of course, failed again in `int24`). Or even better, add an option to convert integer to byte array like `text/binary`.

So is there any problem with this change and do you have plan to do so?

**Comment by osheroff** [comment]
I'm about 99.9% sure you can't just remove the cast to `int` without breaking all the consumers.

`mysql-binlog-connector` doesn't know whether an integer is signed or unsigned either.  Nobody without a copy of the schema knows.  So whether a column was signed or unsigned still need to be provided by the user, but yeah, binlog-connector could help out some by preserving the length of the column.  

Search this repo for `CHAR_AND_BINARY_AS_BYTE_ARRAY` -- that would be the pattern you'd need to follow to have the configuration flag that enables this behavior.

**Comment by zzt93** [comment]
OK, I will have a try.
