### ISSUE TITLE
CHANGELOG missing latest release

### ISSUE THREAD

**Issue by Chrizpy** [osheroff/mysql-binlog-connector-java#20]
The changelog seems to be missing an entry for the latest version `0.23.2`.

**Comment by walro** [comment]
The tag is also missing.

Moreover, `0.23.1` is also missing in the changelog. However, as that version is tagged, the following works: https://github.com/osheroff/mysql-binlog-connector-java/compare/0.22.2...0.23.1 (and on the same subject I suppose https://github.com/osheroff/mysql-binlog-connector-java/compare/0.23.1...2e6147bc81ac458a7325e220840be285388a0145 would be the closest we can get to 0.23.2 for now)

**Comment by osheroff** [comment]
fixed
