### ISSUE TITLE
When mysql column type is int unsigned , sometimes the value read from binlog is negative number

### ISSUE THREAD

**Issue by waywtd** [osheroff/mysql-binlog-connector-java#29]
When mysql column type is int unsigned , the value read from binlog is negative number;
when the value is 4294967295, and the type of column from the binlog  is int,and the value is -1

**Comment by osheroff** [comment]
Yes, unfortunately this is not possible to fix at the bin log level.  You need the schema from maxwell or debezium in order to know whether an integer is signed or not.  Sorry!
