### ISSUE TITLE
Cut release to incorporate latest binlog compatibility fix

### ISSUE THREAD

**Issue by wilsoniya** [osheroff/mysql-binlog-connector-java#52]
Hi there, @osheroff!  I see that #41 has been merged; thank you for tackling that! Would you be willing to cut another release so these important fixes can be used by dependent software (e.g., Debezium)? This would be a major help to my work. 

Thank you!

**Comment by gunnarmorling** [comment]
+1 for a release with this fix :)

**Comment by osheroff** [comment]
v0.25.3 was released last month with the fix...

**Comment by wilsoniya** [comment]
Thank you @osheroff ! I see the release `0.25.3` release in maven, but it looks like somehow the version hasn't actually been bumped in master: https://github.com/osheroff/mysql-binlog-connector-java/blob/feb9221a54d79911e9b82c19ff9ed6034850b84b/pom.xml#L7

**Comment by osheroff** [comment]
roger.  pushed.
