### ISSUE TITLE
the update event can't resolve fields name?

### ISSUE THREAD

**Issue by biuabiu** [osheroff/mysql-binlog-connector-java#54]
`UpdateRowsEventData{tableId=119, includedColumnsBeforeUpdate={0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, includedColumns={0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, rows=[
    {before=[xxx], after=[xxx]}
]}`

**Comment by osheroff** [comment]
not a bug in binlog-connector-java, a mysql limitation.  maxwell and debezium both have to go to ungodly lengths to get fields names.

**Comment by bluebike** [comment]
Note...
Older MySQL/MariaDB binlog doesn't contain information about field names.
MySQL 8.0+  and MariaDB 10.5+ have extended metadata which contain data like: 
* column names
* column charset 
* signedness of number columns
* enum/set values (those are transmitted as numbes in binary log)
* primary key
* ... 

Library parses data data to TableMapEventMetaData structure. 

https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_row_metadata

https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/TableMapEventMetadata.java

https://mariadb.com/kb/en/changes-improvements-in-mariadb-105/#binary-log-and-replication-more-metadata
