### ISSUE TITLE
Using mariadb_slave_capability=1 breaks GTID events

### ISSUE THREAD

**Issue by mdleonid** [osheroff/mysql-binlog-connector-java#87]
With release [0.27.1](https://github.com/osheroff/mysql-binlog-connector-java/compare/0.27.0...0.27.1) ([this commit](https://github.com/osheroff/mysql-binlog-connector-java/commit/96446c52a68f0324f0cf7dec1e182cfb72d2c0f1) specifically).

With `mariadb_slave_capability=1` the connector does not get `MARIADB_GTID` events at all. With `mariadb_slave_capability=4` those events are there.

I am not aware of the reasons behind setting the capability mode to `1`, but I would suggest at least making it configurable.

Please, see the attached test-case. It works in 0.27.0 and fails with next versions.

[test-case.zip](https://github.com/osheroff/mysql-binlog-connector-java/files/9809588/test-case.zip)

**Comment by osheroff** [comment]
fixed this in 0.27.4
